on:
  push:
    branches:
     - sandbox

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: Use hello world
    steps:
      - uses: actions/checkout@v2
      - id: modified-packages
        uses: tier4/github-actions/ros-modified-packages@sandbox
        with:
          base-branch: initial
      - shell: bash
        run: echo packages = ${{ steps.modified-packages.outputs.packages }}
